<?php
require_once __DIR__ . '/../bootstrap.php';

// Setup enhancer
require_once __DIR__ . '/GettersEnhancer.php';
\Enhancer\EnhancerStream::$enhancer = new GettersEnhancer;


// Register autoloader
$loader = new \Enhancer\Loaders\ClassLoader;
$loader->register(true);
$loader->add('', __DIR__ . '/classes');


/*****************  tests  *****************j*d*/


$movie = new Movie("The Dark Night Returns", 10);
var_dump($movie->getName(), $movie->getRating()); // methods generated by enhancer

$refl = new ReflectionClass('Movie'); // the methods are real
print_r($refl->getMethods());
